name: Develop to Staging with Squash

on:
  pull_request:
    branches: [staging]
    types: [opened, synchronize, reopened]

jobs:
  squash-and-merge:
    runs-on: ubuntu-latest
    if: github.base_ref == 'staging' && github.head_ref == 'develop'

    steps:
      - name: Checkout develop and staging branches
        uses: actions/checkout@v4
        with:
          ref: develop
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch staging branch
        run: git fetch origin staging:staging

      - name: Analyze commits for squashing
        id: analyze_commits
        run: |
          # Get commits that are in develop but not in staging
          COMMITS_TO_SQUASH=$(git log staging..develop --oneline --no-merges)

          if [ -z "$COMMITS_TO_SQUASH" ]; then
            echo "No commits to squash"
            exit 0
          fi

          # Extract feature branch names from commit messages
          FEATURE_BRANCHES=$(echo "$COMMITS_TO_SQUASH" | grep -oE "(feature|bugfix|hotfix)/[a-zA-Z0-9\-]*" | sort | uniq)

          echo "Commits to squash:"
          echo "$COMMITS_TO_SQUASH"
          echo ""
          echo "Feature branches detected:"
          echo "$FEATURE_BRANCHES"

          # Create a summary for the PR
          echo "squash_summary<<EOF" >> $GITHUB_OUTPUT
          echo "## 📋 Staging Promotion Analysis" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          echo "The following feature branches will be promoted to staging:" >> $GITHUB_OUTPUT
          echo "$FEATURE_BRANCHES" | while read branch; do
            if [ ! -z "$branch" ]; then
              echo "- **$branch**" >> $GITHUB_OUTPUT
            fi
          done >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          echo "### Original Commits:" >> $GITHUB_OUTPUT
          echo '```' >> $GITHUB_OUTPUT
          echo "$COMMITS_TO_SQUASH" >> $GITHUB_OUTPUT
          echo '```' >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Prepare staging promotion information
        if: steps.analyze_commits.outputs.squash_summary != ''
        run: |
          echo "🚀 Preparing staging promotion information..."

          echo "✅ Staging promotion analysis completed"
          echo "📋 GitHub's built-in squash will handle commit squashing on merge"

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });

            const botComment = comments.find(comment =>
              comment.user.type === 'Bot' &&
              comment.body.includes('Commit Squashing Plan')
            );

            if (botComment) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: `${{ steps.analyze_commits.outputs.squash_summary }}`
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: `${{ steps.analyze_commits.outputs.squash_summary }}`
              });
            }
